kcpq_server: 'al.cctv.mba:4000'
kcpq_subject: 'h264.stream'
nats_server: 'nats://cctv.mba:4222'
nats_subject: 'h264.stream'
aes256_key_hex: '868af252ba94b53544998d998f359490ce536c258de7e29fe8c16b5ee7ffc700'
stats_interval: 10
auto_reconnect: true
reconnect_interval: 5
use_channel_mode: true
